before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    id: "codeartoken"
    binary: "codeartoken"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    id: "codeartoken"
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      amd64: x64
      386: i386
    format_overrides:
      - goos: windows
        format: zip
universal_binaries:
  - replace: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - 
    tap:
      owner: manojkarthick
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    homepage: "https://github.com/manojkarthick/codeartoken"
    description: "Refresh AWS CodeArtifact credentials for Maven"
    license: "MIT"
